-- Estructura y datos para bloques de conocimiento y relación con asignaturas
begin;

-- Tabla de bloques de conocimiento (idempotente)
create table if not exists public.bloques_conocimiento (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now()
);

-- Relación: cada asignatura pertenece a un bloque de conocimiento
alter table public.asignaturas add column if not exists bloque_conocimiento_id bigint;

-- Foreign key (tolerante a re-ejecución)
do $$
begin
  alter table public.asignaturas
    add constraint asignaturas_bloque_conocimiento_id_fkey
    foreign key (bloque_conocimiento_id)
    references public.bloques_conocimiento(id);
exception when duplicate_object then
  null;
end $$;

-- Registros iniciales de bloques de conocimiento
insert into public.bloques_conocimiento (nombre) values
  ('Ciencias Básicas de la Ingeniería'),
  ('Tecnologías Básicas'),
  ('Tecnologías Aplicadas'),
  ('Ciencias y Tecnologías Complementarias')
on conflict (nombre) do nothing;

commit;