BEGIN;
TRUNCATE TABLE public.asignaturas RESTART IDENTITY CASCADE;
INSERT INTO public.asignaturas (nombre) VALUES
('Álgebra y Geometría Analítica'),
('Análisis Matemático I'),
('Física I'),
('Programación, Algoritmos y Estructuras de Datos'),
('Matemática Discreta'),
('Teoría de Sistemas'),
('Idioma Extranjero'),
('Ingeniería de Software I'),
('Paradigmas de Programación'),
('Análisis Matemático II'),
('Cálculo Numérico'),
('Física II'),
('Ingeniería y Sociedad'),
('Organización y Arquitectura de Computadoras'),
('Probabilidad y Estadística'),
('Bases de Datos'),
('Ingeniería de Software II'),
('Diseño Web'),
('Sistemas Operativos'),
('Teoría de la Información y la Comunicación'),
('Autómatas y Gramáticas'),
('Desarrollo Back End'),
('Legislación'),
('Modelos y Simulación'),
('Redes de Computadoras'),
('Ingeniería de Software III'),
('Desarrollo Front End'),
('Inteligencia Artificial'),
('Optativa I'),
('Seguridad Informática'),
('Arquitectura de Software'),
('Auditoría Informática'),
('Calidad de Software'),
('Optativa II'),
('Práctica Profesional Supervisada'),
('Organización Empresarial'),
('Sistemas de Información'),
('Economía y Finanzas'),
('Emprendedorismo Tecnológico'),
('Gestión de Servicios TIC'),
('Proyecto Integrador'),
('Formulación de Propuesta de Proyecto Integrador'),
('Formulación y Evaluación de Proyectos TIC')
ON CONFLICT (nombre) DO NOTHING;
COMMIT;